### ISSUE TITLE
매복상태에서 적 공격시 아군 머리위로 '발각' 글씨가 안 뜹니다

### ISSUE THREAD

**Issue by queensale** [MerHS/bkgirl-i18n#12]
[스샷](http://gall.dcinside.com/mgallery/board/view/?id=bjsn&no=2700790)

아군 머리 위로 빨간 한자 뜨는 게 출력이 안되고 있습니다.

아마 번역 안돼있는 글자는 전부 안나오는 거 같아요.
섬광탄의 '현기증' 이나 수류탄의 '제압' 은 item-resources xml에 번역이 돼 있어서 제대로 표시가 됩니다.
멘도 경기관총 공격시 제압효과나 기관총탑 공격시 제압효과도 표시 안되고 있는 것 같아요.

그 텍스트가 어디 있는 건지 찾아서 한글로 바꿔넣어 주시면 해결될 거 같습니다.

**Comment by MerHS** [comment]
알파 2 버전에서 번역은 했으나 제대로 들어갔는지는 확인이 필요합니다.

**Comment by queensale** [comment]
어제 되는거 확인했습니다
