### ISSUE TITLE
알파2 버그리폿

### ISSUE THREAD

**Issue by queensale** [MerHS/bkgirl-i18n#14]
새 게임으로 진행하면 글자 누락 없이 잘 됩니다
기존 세이브파일은 하드코딩된 부분 글자 여전히 안나오는데 새 게임으로 시작하면 문제없어요
일단 1장 깨서 정비창 나오는 부분까지 해보겠습니다

**Comment by queensale** [comment]
정비창도 문제없습니다
쭉 진행해 볼게요

**Comment by queensale** [comment]
![_2019_01_18_01_52_07_244](https://user-images.githubusercontent.com/46735204/51338382-01a94880-1acd-11e9-9af3-19ab6f9ffbe7.png)
'포기'는 '해제'로 수정했습니다
'펄스발생기'가 너무 길어서 '펄서'로 수정했습니다

![_2019_01_18_02_16_16_833](https://user-images.githubusercontent.com/46735204/51338397-0837c000-1acd-11e9-88b2-45a45ce15de8.png)
'데이터 수신 중' 은 '획득한 문서' 로 수정했습니다

**Comment by queensale** [comment]
근데 이겜 세이브파일 어디 저장되는지 아세요? 설치폴더에도 없고 사용자 폴더에도 없는거같고...
싹 다 지우고 재시작해보고 싶은데 어딨는질 모르겠네요

**Comment by MerHS** [comment]
unity 세이브 파일은 보통 C://Users/(windows 계정명)/AppData/LocalLow 안의 폴더 중 하나에 있습니다.
지금 윈도우 환경이 아니라 확인을 못하겠네요

**Comment by queensale** [comment]
아 찾았습니다
C:\Users\계정명\AppData\LocalLow\StudioGameMaster\Bakery Girl
여깄네요 감사합니다
