### ISSUE TITLE
……… 3점 폰트 없음

### ISSUE THREAD

**Issue by MerHS** [MerHS/bkgirl-i18n#2]
전부 온점 3개  ...로 바꿔야 한다

**Comment by MerHS** [comment]
가능하면 이제부턴 여기다 리폿해주세요
crowdin 10일 후면 계정 만료됩니다

**Comment by queensale** [comment]
아 그렇군요 일단 crowdin에서 lv10, lv11, lvinfinite, secret-resources 는 수정해 뒀습니다

**Comment by MerHS** [comment]
Duplicates https://github.com/MerHS/bkgirl-i18n/issues/10
