### ISSUE TITLE
임무결과창 미번역부분과 글자 안나오는부분

### ISSUE THREAD

**Issue by MGDoubleO** [MerHS/bkgirl-i18n#9]
![_2019_01_16_05_15_45_681](https://user-images.githubusercontent.com/46725747/51207357-eebc3a00-194d-11e9-8001-5054ef67316e.png)

- 좌상단에 한자로 "획득정보"라고 나오는 부분이 미번역
- 우상단에 챕터명 한글이 짤림

**Comment by MerHS** [comment]
해결
